---

- name: PLAY-START
  hosts: servers
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
      
      - name: Disallow password authentication for Ubuntu server
        lineinfile: dest=/etc/ssh/sshd_config
                    regexp="^PasswordAuthentication yes"
                    line="PasswordAuthentication no"
                    state=present
        when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic"
        notify: Restart ssh
      
      - name: Disallow password authentication for CentOS server
        lineinfile: dest=/etc/ssh/sshd_config
                    regexp="^#PasswordAuthentication yes"
                    line="PasswordAuthentication no"
                    state=present
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
        notify: Restart ssh

      - name: Disallow root SSH access for Ubuntu server
        lineinfile: dest=/etc/ssh/sshd_config
                    regexp="^PermitRootLogin prohibit-password"
                    line="PermitRootLogin no"
                    state=present
        when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic"
        notify: Restart ssh

      - name: Disallow root SSH access for CentOS server
        lineinfile: dest=/etc/ssh/sshd_config
                    regexp="^#PermitRootLogin yes"
                    line="PermitRootLogin no"
                    state=present
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
        notify: Restart ssh
        
      - name: Timeout SSH Connection for All server
        lineinfile: dest=/etc/ssh/sshd_config
                    regexp="^#ClientAliveInterval 0"
                    line="ClientAliveInterval 300"
                    state=present
        notify: Restart ssh

  handlers:
  - name: Restart ssh
    service: name=sshd state=restarted
