---

- name: PLAY-START
  hosts: servers
  gather_facts: yes
  become: yes
  become_user: root
  
  tasks:
      - name: install apache on Ubuntu
        apt: name=apache2 update_cache=no state=latest
        when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic"

      - name: install httpd on CentOS
        yum: name=httpd update_cache=no state=latest
        notify:
        - restart httpd
        when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
